### ISSUE TITLE
CreateExample fails if there are more than one Record Types named 'Template'

### ISSUE THREAD

**Issue by dschultz-mo** [mshanemc/InspectAnything#1]
Shane,

My org already had a record type named 'Template' so when I tried to create the example template, the code at line 199 returned more than one Record Type.  I modified the line to the following:

`i.recordTypeId = [select id from recordType where name = 'Template' and SobjectType = 'Inspection__c'][0].Id;`

**Comment by mshanemc** [comment]
Nice catch!  Wanna do the PR?

**Comment by dschultz-mo** [comment]
Shane, so far all I have gotten done is install and try to create the sample template.  I'll play with it a little more this week and then work on fixes for anything I find.

**Comment by mshanemc** [comment]
closed by @dschultz-mo PR-1.
